name = "KUCMC"
license = "MIT"
description = "KUCMC WEBSITE"

min_version = "0.121.2"

tags = [
  "KUCMC"
  "Kathmandu University"
  "Computational Mathematics"
  "CM"
  "KU Mathematics"
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "KUCMC


[original]
author = "KUCMC"
